openapi: 3.0.0
info:
  title: Miele API Monitoring
  version: 1.0.0
servers:
  - url: https://api.mcs3.miele.com/v1
paths:
  /devices:
    get:
      summary: Returns all information about all appliances linked to an user account
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized
